### ISSUE TITLE
How to shrink height of window when using Bottom option

### ISSUE THREAD

**Issue by GitMurf** [jiaoshijie/undotree#13]
First off, awesome plugin! Thanks for the hardwork :)

A couple questions:

1. when choosing the bottom position in config, how do I shrink the height? Everything I try still ends up with the undo window covering almost my entire screen.
2. when I have a large undo history, the "branches" or paths of the undo continues to grow more and more to the right adding new branches. Is this expected? Is this expected? Any tips?

![image](https://github.com/jiaoshijie/undotree/assets/64155612/22178507-4dbc-4865-97aa-b30f07b66fdb)

**Comment by jiaoshijie** [comment]
1. I fixed this problem, now the height of the undotree window should be a normal size. And you also can set the height using the code below.
```lua
undotree.setup({
-- ......
position = "bottom",
window = {
    -- ......
    height = 30,  -- set the height of undotree window, and also set the height of diff window if you don't use float diff window
},
-- ......
})
```
2. If I understand correctly, the answer is yes. Because it is simple and clear to see the branches.

**Comment by GitMurf** [comment]
Thanks! it worked
