### ISSUE TITLE
splits are too big

### ISSUE THREAD

**Issue by omaru-ok** [jiaoshijie/undotree#8]
how do i make it bit small? 

![image](https://user-images.githubusercontent.com/108952834/235300501-74d983d8-7d90-4447-a1f2-95eefb8be3f8.png)

**Comment by jiaoshijie** [comment]
Update this plugin, and try to set window = { winblend = 51, width = **number**, }. But I think it maybe is other plugin's behavior.

**Comment by omaru-ok** [comment]
float window is buged , and im noob i have not much info , sorry
